App\Entity\ActionFile:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [action, title]
        errorPath: title
        message: "Le nom du fichier {{ value }} est déjà déclaré dans cette action."
  properties:
    title:
      - NotBlank: ~
      - Length:
          min: 3
          max: 255
          minMessage: "Le nom du lien {{ value }} doit avoir plus de 2 caractères"
          maxMessage: "Le nom du lien {{ value }} ne peut pas avoir plus de 255 caractères"
